### ISSUE TITLE
 failed to start process, "babel-node" exec not found

### ISSUE THREAD

**Issue by linocatucci** [rwieruch/node-babel-server#2]
hello,
I have followed your steps in the tutorial but I end up with an error:
```
[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/index.js`
sh: babel-node: command not found
[nodemon] failed to start process, "babel-node" exec not found
[nodemon] Error
    at Bus.utils.bus.on (/usr/local/lib/node_modules/nodemon/lib/nodemon.js:147:25)
    at Bus.emit (events.js:187:15)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nodemon/lib/monitor/run.js:145:11)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
```

I have searched on stackoverflow but I can't solved the problem.
Can you help me?

Best regards,
Lino

**Comment by rwieruch** [comment]
Did you try clone this repository as well? To verify that nothing is wrong with what you have done in the tutorial, maybe you could try out this repository and check whether you experience the same error. Let me know, then I can help more with it!

**Comment by linocatucci** [comment]
Hi,
I have done exactly how you describe it in your steps. The only this is is that I have cloned the repo with : git clone https://github.com/rwieruch/node-babel-server.git.

I am still getting the error: 
```
[nodemon] starting `babel-node src/index.js`
sh: babel-node: command not found
[nodemon] failed to start process, "babel-node" exec not found
[nodemon] Error
```
My package.json is like this:

```
{
  "name": "node-babel-server",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon --exec babel-node src/index.js",
    "test": "echo \"No test specified\" && exit 0"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/node": "^7.0.0",
    "@babel/preset-env": "^7.1.6",
    "nodemon": "^1.18.7"
  },
  "dependencies": {
    "dotenv": "^6.1.0"
  }
}

```

**Comment by linocatucci** [comment]
Hi Robin,
I have used your other tutorial (https://www.robinwieruch.de/minimal-node-js-babel-setup/) to create my own boilerplate and this works. 
I can continue with the other tutorial :).

Thanks for your reply.
Lino

**Comment by rwieruch** [comment]
Glad it worked for you now. I keep this issue open, in case anyone else stumbles upon this.

**Comment by Arwiz** [comment]
I faced the same issue. I reinstalled @babel/node and it fixed the issue. 
npm install --save-dev  @babel/node

**Comment by alextjd** [comment]
Can confirm that cloning the repo, doing _npm i_ and then _npm run start_ still gives me the **"babel-node" is not recognized as an internal or external command** :(

Using: windows 10, npm 7.8 and node 14.16

**Comment by reggiolee** [comment]
I fixed it by change the script to "nodemon --exec ./node_modules/.bin/babel-node src/index.js", but i still not found where the real problem is _(:з」∠)_

**Comment by pranavwani** [comment]
> I faced the same issue. I reinstalled @babel/node and it fixed the issue. npm install --save-dev @babel/node

Works perfirectly

**Comment by rwieruch** [comment]
Updated all dependencies here and pushed the code. Thanks for reporting and thanks for the fix @Arwiz !
